matrix:
  include:
    # System configuration
    sudo: required
    dist: trusty
    
    # Angular Frontend
    - language: node_js
      node_js: '7'

      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
            - google-chrome-beta

      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start

      before_script:
        - cd frontend
        - npm install -g angular-cli
        - npm install -g karma
        - npm install
        - ng build

      after_script:
        - cd ..

      script: karma start karma.conf.js --single-run

    # Java Backend
    - language: java
      
      before_script:
        - cd backend
      script:
        - ./gradlew assemble
        - ./gradlew build
      after_script:
        - cd .. 
