matrix:
  include:
<<<<<<< HEAD
=======
    - language: java
      before_script:
        - cd backend
      script:
        - ./gradlew assemble
        - ./gradlew build
      after_script:
        - cd ..

>>>>>>> development
    - language: node_js
      node_js:
        - "7"
      before_script:
        - cd frontend
        - npm install
      script:
        - ng build
      after_script:
        - cd ..
